### ISSUE TITLE
Create endpoint to create new Authelia user

### ISSUE THREAD

**Issue by miguel-merlin** [stevensblueprint/techops#18]
## Description
Authelia uses the following command to add a new user 
Create endpoint that modifies users.yaml

**Comment by ericzty** [comment]
`authelia storage user identifiers add john --identifier f0919359-9d15-4e15-bcba-83b41620a073` command won't work since we're using the file backend, we will just have to append to the users.yml file

**Comment by miguel-merlin** [comment]
Yeah. I'm updating the YAML file now

**Comment by miguel-merlin** [comment]
Moved to User Management API
